# Ubuntu 18.04 + TeXlive 2017
# https://gitlab.com/axelsommerfeldt/docker-texlive
ubuntu_18.04:
  image: axelsommerfeldt/texlive:ubuntu_18.04
  stage: test
  script:
    - ./test.sh -d test/fallback -d test/keyfloat -d test/thesis -d issues/gitlab/issue_23a.tex -d issues/gitlab/issue_23b.tex -d issues/gitlab/issue_34.tex -o ubuntu_18.04.xml
      # The thesis document class is not part of TeXlive 2017
      # issues/gitlab/issue_23?.tex need at least KOMA-Script 3.25 (but TeXlive 2017 only offers 3.24)
      # issues/gitlab/issue_34.tex needs a newer version of pdfx
  artifacts:
    reports:
      junit: ubuntu_18.04.xml

# Ubuntu 20.04 + TeXlive 2019
# https://gitlab.com/axelsommerfeldt/docker-texlive
ubuntu_20.04:
  image: axelsommerfeldt/texlive:ubuntu_20.04
  stage: test
  script:
    - ./test.sh -d test/thesis -o ubuntu_20.04.xml
      # The thesis document class is not part of TeXlive 2019
  artifacts:
    reports:
      junit: ubuntu_20.04.xml

# Latest Ubuntu (currently 20.10 + TeXlive 2020)
# https://gitlab.com/axelsommerfeldt/docker-texlive
ubuntu_latest:
  image: axelsommerfeldt/texlive:ubuntu_latest
  stage: test
  script:
    - ./test.sh -d test/thesis -o ubuntu_latest.xml
      # The thesis document class is not part of TeXlive 2020
  artifacts:
    reports:
      junit: ubuntu_latest.xml

# MikTeX
# https://miktex.org/howto/miktex-docker
miktex:
  image: miktex/miktex
  stage: test
  when: manual
  script:
    - initexmf --admin --default-paper-size=a4 --enable-installer --engine=pdftex --force --mkmaps --update-fndb
    - ./test.sh -o miktex.xml test/ntg/fonts.tex
  artifacts:
    reports:
      junit: miktex.xml

# TeXlive
# https://nico.dorfbrunnen.eu/de/posts/2020/docker-latex/
# https://gitlab.com/islandoftex/images/texlive
latest:
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  stage: test
  when: manual
  script:
    - ./test.sh -o latest.xml
  artifacts:
    reports:
      junit: latest.xml

